---
title: "The R Manuals"
subtitle: "A re-styled version of the original R manuals"
format:
  html:
    toc: false
execute:
  echo: false
---

```{r, message = FALSE}
library(htmltools)
library(fs)
pkgload::load_all(here::here())
```



This is a restyled version of the R manuals, originally provided by the *R Development Core team*.


---

The primary aim of this site is to provide a re-styled and searchable version of the manuals, but we try very hard to keep the actual content as close to the original as possible.  The r-styling consists mainly of:

* Splitting chapters into separate pages
* Add code formatting

Original R Manuals can be found at <https://cran.r-project.org/manuals.html>. The manuals in this website are built automatically from the originals using [Quarto](https://quarto.org). Code can be found at <https://github.com/rstudio/r-manuals>.

The original license from the R Core development team explicitly allows modified versions of the original manual, under these terms:

> Permission is granted to make and distribute verbatim copies of this manual provided the copyright notice and this permission notice are preserved on all copies.
> Permission is granted to copy and distribute modified versions of this manual under the conditions for verbatim copying, provided that the entire resulting derived work is distributed under the terms of a permission notice identical to this one.
